2023-05-24 01:08:32,804 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 230221ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 01:19:19,812 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 606994ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 01:35:24,591 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 924773ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 02:39:02,875 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 941784ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 02:54:49,303 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 906243ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 03:59:35,855 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 946512ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 04:29:47,836 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 911903ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 04:47:50,128 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1022302ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 05:04:48,448 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 978327ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 05:53:03,280 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 969574ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 06:23:13,916 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 910567ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 06:55:15,907 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 921522ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 07:25:32,207 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 916204ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 07:42:24,305 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 952079ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 07:58:39,656 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 935368ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 08:29:54,599 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 974854ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 08:46:14,597 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 919993ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 09:03:00,612 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 966009ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 09:34:17,501 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 976837ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 10:21:41,743 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 905677ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 10:39:11,129 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1009368ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 11:28:30,034 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 983321ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 11:45:35,864 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 985792ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 12:02:29,417 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 973545ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 12:59:23,528 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 973943ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 14:11:56,907 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 471219ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 14:28:03,753 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 926816ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 14:44:47,286 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 943534ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 15:42:41,595 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 949284ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 15:58:38,968 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 917366ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 16:29:28,901 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 949889ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 16:48:23,477 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1074562ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 18:24:42,270 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 1031961ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 18:41:10,618 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 948343ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 18:57:16,063 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 925418ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 19:28:56,700 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 980546ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-24 19:38:20,548 ERROR 64282 nodejs.ClusterClientNoResponseError: client no response in 483856ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 64282
hostname: Stone-xdeMacBook-Pro.local

2023-05-25 12:41:13,433 ERROR 82715 nodejs.ClusterClientNoResponseError: client no response in 615300ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 82715
hostname: Stone-xdeMacBook-Pro.local

2023-05-25 12:57:38,741 ERROR 82715 nodejs.ClusterClientNoResponseError: client no response in 945277ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 82715
hostname: Stone-xdeMacBook-Pro.local

2023-05-25 13:13:58,296 ERROR 82715 nodejs.ClusterClientNoResponseError: client no response in 939527ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 82715
hostname: Stone-xdeMacBook-Pro.local

2023-05-25 14:01:47,642 ERROR 82715 nodejs.ClusterClientNoResponseError: client no response in 972713ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 82715
hostname: Stone-xdeMacBook-Pro.local

2023-05-25 14:17:58,881 ERROR 82715 nodejs.ClusterClientNoResponseError: client no response in 931257ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 82715
hostname: Stone-xdeMacBook-Pro.local

2023-05-25 14:50:30,249 ERROR 82715 nodejs.ClusterClientNoResponseError: client no response in 982920ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 82715
hostname: Stone-xdeMacBook-Pro.local

2023-05-25 15:25:40,802 ERROR 82715 nodejs.ClusterClientNoResponseError: client no response in 1017291ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 82715
hostname: Stone-xdeMacBook-Pro.local

2023-05-25 15:45:26,414 ERROR 82715 nodejs.ClusterClientNoResponseError: client no response in 285537ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 82715
hostname: Stone-xdeMacBook-Pro.local

2023-05-25 15:53:18,599 ERROR 90398 [-/127.0.0.1/-/0ms GET /] nodejs.ER_ACCESS_DENIED_ERRORError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Sequence._packetToError (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Protocol._enqueue (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/mysql/lib/Pool.js:48:16)
    at node:internal/util:367:7
    at new Promise (<anonymous>)
    at Pool.getConnection (node:internal/util:353:12)
    at Pool.query (/Users/stone_x/Desktop/Personal Ledger/backend/node_modules/mysql/lib/Pool.js:202:8)
    at node:internal/util:367:7
    at new Promise (<anonymous>)
    sql: select now() as currentTime;
code: "ER_ACCESS_DENIED_ERROR"
errno: 1045
sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)"
sqlState: "28000"
fatal: true
name: "ER_ACCESS_DENIED_ERRORError"
pid: 90398
hostname: Stone-xdeMacBook-Pro.local

